name: money_investment_track
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.6+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  animated_segmented_tab_control: ^2.0.0
  lottie:
  hive_generator:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  google_fonts: ^2.3.2
  pie_chart: ^5.4.0
  flutter_launcher_icons: ^0.14.1
  animated_text_kit: ^4.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "asset/logo/lcslogo.png"
  min_sdk_android: 24
  provider: ^6.1.2
  url_launcher:
  image_picker: ^1.1.2
  adaptive_icon_background : '#ffffff'
  adaptive_icon_foreground : "asset/logo/lcslogo.png"
flutter:
  uses-material-design: true
  assets:
    - asset/coin.png
    - asset/human_avator.png
    - asset/money_bag.png
    - asset/screenAnimate/bottomRectangle.png
    - asset/screenAnimate/topRectangle.png
    - asset/person/maleStudent.png
    - asset/backButton/backButtonCurrency.png
    - asset/backButton/backButtonType.png
    - asset/investingCurrencyPic/star.png
    - asset/investingCurrencyPic/ton.png
    - asset/logo/lcslogo.png
    - lottieJson/emptyShow.json
    - asset/logo/tonQr.jpg
    - asset/jsonAnimation/developer.json
    - asset/SocialIcon/telegramIcon.png
    - asset/SocialIcon/telegramQr.jpg
    - asset/SocialIcon/viberIcon.png
    - asset/SocialIcon/viberQr.png
    - asset/jsonAnimation/subscribe.json
  fonts:
    - family: Jersey
      fonts:
        - asset: fonts/Jersey15-Regular.ttf
    - family: JainiPurva
      fonts:
        - asset: fonts/JainiPurva-Regular.ttf
